POST http://localhost:4444/
Content-Type: application/json

{
  "query": "query SearchPerson { person(name: \"philip\") { name phone id } }"
}
###
POST http://localhost:4444/
Content-Type: application/json

{
  "query": "query SearchPerson { person(name: \"Abbigail Robles\") { name phone id } }"
}